version: 2
jobs:
  build:
    macos:
      xcode: 12.3.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: brew install gh
      # cat ~/.config/gh/hosts.yml | base64 | pbcopy
      - run: mkdir -p ~/.config/gh && echo $GH_CONFIG | base64 -d > ~/.config/gh/hosts.yml
      - run: gh config set -h github.com git_protocol ssh
      - run: gh auth status
      - run: brew tap mherod/tap && brew update
      - run: brew install --verbose resharkercli && resharkercli --help && brew uninstall resharkercli
      - run: brew install --verbose --build-bottle resharkercli && brew bottle resharkercli
      - run: bash upload-bottles.sh
      - run: brew cleanup
