version: 2
jobs:
  build:
    macos:
      xcode: 12.3.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
#      - checkout
      
      - run: brew tap mherod/tap && brew update

      - run: brew install --verbose resharkercli && resharkercli --help && brew uninstall resharkercli
      - run: brew install --verbose --build-bottle resharkercli && brew bottle resharkercli
      
      - store_artifacts:
          destination: out
          path: ~/repo/

      - run:
          name: Brew cleanup
          command: brew cleanup
          when: always