version: 2
jobs:
  build:
    macos:
      xcode: 12.3.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - javacache-{{ checksum ".circleci/config.yml" }}-{{ .Revision }}
            - javacache-{{ checksum ".circleci/config.yml" }}-
            - javacache-

      - run:
          name: Brew doctor
          command: brew doctor
          background: true
      - run:
          name: Install project build tools
          command: bash install-sdkman-tools.sh
          background: true
      - run:
          name: Prepare homebrew and additional build tools
          command: brew update && brew install gh

      # cat ~/.config/gh/hosts.yml | base64 | pbcopy
      - run:
          name: Writing gh configuration
          command: mkdir -p ~/.config/gh && echo $GH_CONFIG | base64 -d > ~/.config/gh/hosts.yml
      - run:
          name: Check GitHub auth status
          command: gh config set -h github.com git_protocol ssh && gh auth status

      - run:
          name: Tap tap tap in
          command: brew tap mherod/tap

      #      - run: brew install --verbose resharkercli && resharkercli --help && brew uninstall resharkercli
#      - run: brew install --verbose --build-bottle resharkercli && brew bottle resharkercli
#      - run: resharkercli --help
      - run: sdk env && gradle brewBottleUploadResharkercli

      #      - run: sdk env && bash upload-bottles.sh
      #      - run: sdk env && kscript edit-formula.sh

      #      - run: git pull --rebase --autostash && git add Formula
      #      - run: git commit -m "[automatic] update formulas" && git push origin

      - save_cache:
          key: javacache-{{ checksum ".circleci/config.yml" }}-{{ .Revision }}
          paths:
            - /Users/distiller/Library/Caches/Homebrew/java_cache
          when: always

      - run: brew cleanup
