jobs:
  build12:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    macos:
      xcode: 12.3.0
    steps:
      - run:
          command: brew doctor --verbose && brew update --verbose
          name: Prepare Homebrew
      - checkout
      - restore_cache:
          keys:
            - javacache-{{ checksum ".circleci/config.yml" }}-{{ .Revision }}
            - javacache-{{ checksum ".circleci/config.yml" }}-
            - javacache-
      - run:
          command: bash install-sdkman-tools.sh
          name: Install project build tools via sdkman
      - run:
          command: brew install gh || brew install --build-from-source gh
          name: Install project build tools via Homebrew
      - run:
          command: mkdir -p ~/.config/gh && echo $GH_CONFIG | base64 -d > ~/.config/gh/hosts.yml
          name: Writing gh configuration
      - run:
          command: gh config set -h github.com git_protocol ssh && gh auth status
          name: Check GitHub auth status
      - run:
          command: git branch --set-upstream-to=origin/$CIRCLE_BRANCH $CIRCLE_BRANCH
          name: Set git upstream
      - run:
          command: brew tap mherod/tap
          name: Tap tap tap in
      - run:
          command: sdk env && gradle brewBottlePublish
          name: Build and upload bottles, commit Formula update
      - run:
          command: git pull --rebase --autostash && git push origin
          name: Pull again (rebase) and push
      - save_cache:
          key: javacache-{{ checksum ".circleci/config.yml" }}-{{ .Revision }}
          paths:
            - /Users/distiller/Library/Caches/Homebrew/java_cache
          when: on_success
      - run: brew cleanup
    working_directory: ~/repo
version: 2
workflows:
  version: 2
  commit:
    jobs:
      - build12

